services:
  - type: web
    name: painel-admin
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: painel-admin-db
          property: connectionString"
